name: water_potability_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - mlflow
  - pip:
    - mlflow-skinny
