name: water-potability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - mlflow==2.10.0
    - scikit-learn==1.3.0
    - pandas==2.0.3
    - matplotlib==3.7.2
    - seaborn==0.12.2
